#!/usr/bin/ruby

require 'nokogiri'

outputfile = "books.csv"

files = Dir['40436*.xml'];

if files.count > 0
  File.open(outputfile, 'w') do |f|
    f.puts "productid;name;articleid;date created;text;tie-in;name"
    files.each do |name|
      doc = Nokogiri::XML(File.open(name))
	
      product = doc.xpath("//product")
      t = Nokogiri::HTML(product.css((product.css("ingress").inner_text.empty?) ? "text" : "ingress").inner_text : , "UTF-8").text
      text = t.split(/\r?\n/)
      if text.length > 0 and text[0].strip.empty? === false
	text = Array.new(2)
        pos = t.index("Tie-in Activity:")
	if pos > -1
	  text[0] = t[0, pos]
	  text[1] = t[pos, t.length]
	else
	   puts t
	end
      else
	puts t
      end
      f.puts(';' + product.css("title").inner_text + ";http://www.earlymoments.com" + product.css("url").inner_text + ";" + product.css("created").inner_text + ";" + ((text.length>0)?text[0]:t).chomp + ";" + ((text.length> 1)?text[1]:"") + ";" + name.force_encoding("UTF-8") )
    end
  end
end
